name: deploy-site
on: 
  push:
    branches:
      # Only deploy when pushing to master branch
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Standard github action to check out repository
      - uses: actions/checkout@v2
      # Set up Node environment
      - run: echo 'Starting build...'
      - uses: actions/setup-node@v3
        with:
          node-version: '10.13.0'
      # Install packages
      - run: yarn install
      # Run vue CLI build
      - run: yarn run build
      # rsync to server
      - run: echo 'Starting deploy...'
      - name: rsync deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SOURCE: dist/
          TARGET: /var/www/dakotaling.com/public_html
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: echo 'Done'